apiVersion: v1
kind: ConfigMap
metadata:
  name: prevent-configmap
data:
  prevent.conf: |
    SECRET_MANAGER={{ .Values.app.config.secretManager }}
    BLOCK_PR={{ .Values.app.config.blockPr }}
    FP_STRICT={{ .Values.app.config.fpStrict }}
    FULL_FINDINGS={{ .Values.app.config.fullFindings }}
    WEBHOOK_PORT={{ .Values.app.config.webhookPort }}
    JWT_EXPIRY_SECONDS={{ .Values.app.config.jwtExpirySeconds }}
