image:
  repository: us-docker.pkg.dev/apiiro/public-images/prevent
  tag: "1.0"
pod:
  containerPort: 8080
resources:
  requests:
    cpu: 0.5
    memory: 100Mi
    ephemeralStorage: 100Mi
  limits:
    cpu: 1
    memory: 200Mi
    ephemeralStorage: 200Mi
# Options secreteManagerType: gcloud, aws, azure, vault
secreteManagerType: gcloud
service:
  clusterIP:
    enabled: true
  NodePort:
    enabled: true
    annotations:
    #- exampleAnnotationKey: 'exampleAnnotationValue'
  port: 80
  targetPort: 8080
externalIngress:
  enabled: false
  gke:
    enabled: false
    annotations:
    #- exampleAnnotationKey: 'exampleAnnotationValue'
    managedCertificate:
      enabled: false
      domain: ""
    frontendConfig:
      enabled: false
      #spec:
      #  frontendConfigSpec:
      #    item1: value1
    backendConfig:
      enabled: false
      #spec:
      #  frontendConfigSpec:
      #    item1: value1